"""LLM-assisted adapter generator for ADAPTABLE plugins.

Produces a Python adapter/bridge wrapper that hosts a foreign (DSH) plugin
inside LeapFlow as a ToolPlugin. Two modes are supported:

- **Template mode** (:func:`generate_adapter_template`): pure string
  formatting from an ``AdapterSpec`` and manifest. No LLM, no I/O, always
  works. Produces a valid ToolPlugin skeleton that proxies each declared
  interface to a subprocess bridge (reusing the SandboxHost pattern).

- **LLM-enhanced mode** (:func:`generate_adapter_with_llm`): given an LLM
  provider, refines the template with more accurate method mappings derived
  from the manifest's declared interfaces. Any failure degrades gracefully
  back to template mode.

File/LLM I/O is confined to the LLM-enhanced path, which is a cold path.
"""

from __future__ import annotations

import asyncio
import inspect
import logging
import re
from typing import Any, List

from leapflow.learning.compatibility.manifest_converter import _normalize_name
from leapflow.learning.compatibility.protocol import AdapterSpec, PluginManifestInput

logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════════════
# Template mode (no LLM)
# ═══════════════════════════════════════════════════════════════════════


def generate_adapter_template(
    spec: AdapterSpec, manifest: PluginManifestInput
) -> str:
    """Generate a Python adapter skeleton from an AdapterSpec (no LLM needed).

    The generated module defines a ToolPlugin class
    ``Dsh{PascalCase(name)}BridgePlugin`` with ``plugin_id`` set to
    ``dsh_{name}_bridge``. It declares one ToolMetadata per declared
    interface (falling back to a single ``invoke`` tool when none are
    declared), and each handler delegates to a SandboxHost subprocess call
    via JSON-RPC.

    Args:
        spec: The AdapterSpec produced by the verdict synthesizer.
        manifest: The parsed manifest of the plugin being adapted.

    Returns:
        A string of valid Python source implementing the bridge adapter.
    """
    dsh_package = manifest.name or "unknown"
    snake = _normalize_name(dsh_package)
    pascal = _pascal_case(snake)
    class_name = f"Dsh{pascal}BridgePlugin"
    plugin_id = f"dsh_{snake}_bridge"
    entry_point = manifest.raw_manifest.get("main", "") if manifest.raw_manifest else ""

    interfaces = list(manifest.declared_interfaces) or ["invoke"]

    tools_block = _render_tools_block(interfaces, dsh_package)
    handlers_block = _render_handlers_block(interfaces)

    return (
        '"""Auto-generated DSH \u2192 LeapFlow bridge adapter.\n'
        "\n"
        "This module was auto-generated by the LeapFlow Plugin Compatibility\n"
        "Assessment Engine (adapter_generator). It wraps the DSH plugin\n"
        f"``{dsh_package}`` and exposes its declared interfaces as a LeapFlow\n"
        "ToolPlugin, proxying each call to a subprocess bridge via JSON-RPC.\n"
        "\n"
        f"Bridge type: {spec.bridge_type}\n"
        f"Target protocol: {spec.target_protocol}\n"
        f"Estimated complexity: {spec.estimated_complexity}\n"
        "\n"
        "Do not edit by hand: regenerate from the source manifest instead.\n"
        '"""\n'
        "\n"
        "from __future__ import annotations\n"
        "\n"
        "from typing import Any, List, Optional\n"
        "\n"
        "from leapflow.plugins.protocol import ToolMetadata\n"
        "from leapflow.plugins.sandbox.sandbox_host import SandboxHost\n"
        "\n"
        "\n"
        f"class {class_name}:\n"
        f'    """Bridge adapter wrapping the DSH plugin ``{dsh_package}``.\n'
        "\n"
        "    Runs the foreign plugin in a subprocess (SandboxHost) and proxies\n"
        "    each declared interface to it via JSON-RPC.\n"
        '    """\n'
        "\n"
        f'    def __init__(self, bridge_module_path: str = "{entry_point}") -> None:\n'
        "        self._bridge_module_path = bridge_module_path\n"
        "        self._host: Optional[SandboxHost] = None\n"
        "\n"
        "    @property\n"
        "    def plugin_id(self) -> str:\n"
        f'        return "{plugin_id}"\n'
        "\n"
        "    @property\n"
        "    def category(self) -> str:\n"
        '        return "bridge"\n'
        "\n"
        "    @property\n"
        "    def dependencies(self) -> List[str]:\n"
        "        return []\n"
        "\n"
        "    def bind_runtime(self, **deps: Any) -> None:\n"
        "        pass\n"
        "\n"
        "    @property\n"
        "    def tools(self) -> List[ToolMetadata]:\n"
        "        return [\n"
        f"{tools_block}\n"
        "        ]\n"
        "\n"
        f"{handlers_block}\n"
        "\n"
        "    async def _invoke_bridge(self, method: str, arguments: dict) -> dict:\n"
        '        """Start the bridge subprocess on first use and proxy one call."""\n'
        "        if self._host is None:\n"
        "            self._host = SandboxHost(self._bridge_module_path)\n"
        "            await self._host.start()\n"
        "        resp = await self._host.invoke(method, arguments)\n"
        "        if resp.ok:\n"
        '            return {"ok": True, "result": resp.result}\n'
        '        return {"ok": False, "error": resp.error}\n'
    )


def _render_tools_block(interfaces: List[str], dsh_package: str) -> str:
    """Render the ToolMetadata entries for the ``tools`` property."""
    entries: List[str] = []
    for iface in interfaces:
        ident = _sanitize_identifier(iface)
        entries.append(
            "            ToolMetadata(\n"
            f'                name="{iface}",\n'
            f"                description=\"Bridged DSH interface '{iface}' "
            f'from {dsh_package}.",\n'
            '                parameters_schema={"type": "object", "properties": {}},\n'
            f"                handler=self._handle_{ident},\n"
            '                x_leapflow={"category": "bridge", "runtime": '
            '"typescript", "bridge": "json_rpc"},\n'
            "            ),"
        )
    return "\n".join(entries)


def _render_handlers_block(interfaces: List[str]) -> str:
    """Render one async handler method per declared interface."""
    defs: List[str] = []
    for iface in interfaces:
        ident = _sanitize_identifier(iface)
        defs.append(
            f"    async def _handle_{ident}(self, **kwargs: Any) -> dict:\n"
            f"        \"\"\"Delegate the '{iface}' call to the DSH subprocess bridge.\"\"\"\n"
            f'        return await self._invoke_bridge("{iface}", kwargs)'
        )
    return "\n\n".join(defs)


def _pascal_case(snake: str) -> str:
    """Convert a snake_case identifier to PascalCase."""
    parts = [p for p in snake.split("_") if p]
    return "".join(p[:1].upper() + p[1:] for p in parts) or "Unknown"


def _sanitize_identifier(name: str) -> str:
    """Sanitize an arbitrary interface name into a valid Python identifier."""
    ident = re.sub(r"\W", "_", name)
    if not ident or ident[0].isdigit():
        ident = "_" + ident
    return ident


# ═══════════════════════════════════════════════════════════════════════
# LLM-enhanced mode (optional)
# ═══════════════════════════════════════════════════════════════════════


def generate_adapter_with_llm(
    spec: AdapterSpec, manifest: PluginManifestInput, llm_provider: Any
) -> str:
    """Generate refined adapter code using an LLM (optional enhancement).

    Falls back to :func:`generate_adapter_template` when ``llm_provider`` is
    ``None`` or when any step of the LLM path fails (invocation error, empty
    output, or output that does not compile). The template is always a valid,
    installable adapter, so degradation never leaves the caller without code.

    Args:
        spec: The AdapterSpec produced by the verdict synthesizer.
        manifest: The parsed manifest of the plugin being adapted.
        llm_provider: A duck-typed provider exposing a text-generation method
            (``generate``/``complete``) or an async ``achat`` interface.

    Returns:
        Refined adapter Python source, or the template on any failure.
    """
    template = generate_adapter_template(spec, manifest)
    if llm_provider is None:
        return template

    try:
        prompt = _build_llm_prompt(spec, manifest, template)
        raw = _invoke_llm(llm_provider, prompt)
        code = _extract_code(raw)
        if not code.strip():
            logger.warning("LLM returned empty adapter; using template")
            return template
        # Validate the refined code compiles before trusting it.
        compile(code, "<generated_adapter>", "exec")
        return code
    except Exception as exc:  # noqa: BLE001 - optional enhancement degrades
        logger.warning(
            "LLM adapter refinement failed (%s); falling back to template", exc
        )
        return template


def _build_llm_prompt(
    spec: AdapterSpec, manifest: PluginManifestInput, template: str
) -> str:
    """Construct the refinement prompt with full manifest and template context."""
    interfaces = ", ".join(manifest.declared_interfaces) or "(none declared)"
    deps = ", ".join(manifest.declared_dependencies) or "(none)"
    return (
        "You are refining an auto-generated LeapFlow bridge adapter for a "
        "foreign (DSH) plugin.\n\n"
        "Target LeapFlow protocol: ToolPlugin — a class exposing "
        "`plugin_id`, `category`, `tools` (list[ToolMetadata]), "
        "`dependencies`, and `bind_runtime(**deps)`. Each tool handler is an "
        "async function proxying to a subprocess bridge (SandboxHost).\n\n"
        f"Source plugin: {manifest.name}@{manifest.version}\n"
        f"Category: {manifest.category}\n"
        f"Source language: {manifest.source_language}\n"
        f"Declared interfaces: {interfaces}\n"
        f"Declared dependencies: {deps}\n"
        f"Bridge type: {spec.bridge_type}\n"
        f"Shim methods: {', '.join(spec.shim_methods) or '(none)'}\n\n"
        "Improve the method mappings and parameter schemas in the following "
        "adapter so each declared interface maps to an accurate handler. "
        "Return only a complete, valid Python module (no prose).\n\n"
        "--- CURRENT TEMPLATE ---\n"
        f"{template}\n"
        "--- END TEMPLATE ---\n"
    )


def _invoke_llm(provider: Any, prompt: str) -> str:
    """Invoke a duck-typed LLM provider and return generated text.

    Tries synchronous ``generate``/``complete`` methods first, then an async
    ``achat`` interface. Raises TypeError when no supported method exists.
    """
    for method_name in ("generate", "complete"):
        method = getattr(provider, method_name, None)
        if callable(method):
            return _coerce_text(method(prompt))

    achat = getattr(provider, "achat", None)
    if callable(achat):
        messages = [{"role": "user", "content": prompt}]
        return _coerce_text(achat(messages, stream=False))

    raise TypeError(
        "llm_provider does not expose a supported generation method "
        "(generate/complete/achat)"
    )


def _coerce_text(result: Any) -> str:
    """Coerce an LLM result (awaitable, string, or response object) into text."""
    if inspect.isawaitable(result):
        result = asyncio.run(result)
    if isinstance(result, str):
        return result
    for attr in ("content", "text", "message"):
        val = getattr(result, attr, None)
        if isinstance(val, str):
            return val
    return str(result)


def _extract_code(raw: str) -> str:
    """Strip Markdown code fences from an LLM response, if present."""
    text = raw.strip()
    if "```" not in text:
        return text
    parts = text.split("```")
    if len(parts) < 2:
        return text
    block = parts[1]
    # Drop an optional language tag on the opening fence line.
    for tag in ("python", "py"):
        if block.startswith(tag):
            block = block[len(tag):]
            break
    return block.strip()
